export const mockData = [
  {
    id: 1,
    title: "Spaghetti Carbonara",
    videoSrc: "/videos/video1.mp4",
    description: "A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.",
    username: "ChefMario",
    avatar: "https://picsum.photos/seed/mario/25",
    views: "1.2K views",
    daysAgo: "2 days ago",
  },
  {
    id: 2,
    title: "Chicken Alfredo",
    videoSrc: "/videos/02.mp4", 
    description: "A creamy and cheesy chicken pasta that’s quick to make.",
    username: "PastaQueen",
    avatar: "https://picsum.photos/seed/pasta/25",
    views: "800 views",
    daysAgo: "3 days ago",
  },
  {
    id: 3,
    title: "Dal chawal",
    videoSrc: "/videos/03.mp4", 
    description: "An exciting new recipe to try out.",
    username: "Biharifood",
    avatar: "https://picsum.photos/seed/foodie101/25",
    views: "1.1M views",
    daysAgo: "5 days ago",
  },
  {
    id: 4,
    title: "Litti Chokha",
    videoSrc: "/videos/04.mp4", 
    description: "An amazing dish that's easy to cook.",
    username: "Nisha Madhuika",
    avatar: "https://picsum.photos/seed/chef-lucy/25",
    views: "1.5M views",
    daysAgo: "12 hours ago",
  },
  {
    id: 5,
    title: "Poha",
    videoSrc: "/videos/05.mp4", 
    description: "Learn how to cook like a pro.",
    username: "Kavita Kitchen",
    avatar: "https://picsum.photos/seed/mastercook/25",
    views: "900 views",
    daysAgo: "1 day ago",
  },
  {
    id: 6,
    title: "Sahee Paneer",
    videoSrc: "/videos/06.mp4", 
    description: "Delicious recipes that everyone will love.",
    username: "CookingNinja",
    avatar: "https://picsum.photos/seed/cookingninja/25",
    views: "3.2K views",
    daysAgo: "3 days ago",
  },
  
];
